INSERT INTO country(code, name) VALUES ('IN', 'India');
INSERT INTO country(code, name) VALUES ('US', 'United States');
INSERT INTO country(code, name) VALUES ('JP', 'Japan');
INSERT INTO country(code, name) VALUES ('AU', 'Australia');
INSERT INTO country VALUES ('ZA','South Africa');
INSERT INTO country VALUES ('LU','Luxembourg');
INSERT INTO country VALUES ('BV','Bouvet Island');
INSERT INTO country VALUES ('DJ','Djibouti');
INSERT INTO country VALUES ('GP','Guadeloupe');
INSERT INTO country VALUES ('SS','South Sudan');
INSERT INTO country VALUES ('GS','South Georgia');
INSERT INTO country VALUES ('TF','French Southern Territories');
INSERT INTO country VALUES ('ZM','Zambia');
INSERT INTO country VALUES ('ZW','Zimbabwe');